pre_tasks:
- hosts: all         
- name: Refresh apt cache
  become: no
  local_action: shell ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=5 {{ inventory_hostname }} sudo apt-get update
   
- name: Install Python-apt to pull in Python
  become: no
  local_action: shell ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=5 {{ inventory_hostname }} sudo apt-get install --no-install-recommends --assume-yes python-apt

- hosts: wordpress
  roles:
    - role: config
  become: yes
  vars_files:
    - inventories/group_vars/all
  vars:
    ansible_ssh_private_key_file: "{{ chave }}"
    ansible_user: "{{ usuario }}"
  