- hosts: wordpress
  roles:
    - role: config
  become: yes
  vars_files:
    - inventories/group_vars/all
  vars:
    ansible_ssh_private_key_file: "{{ chave }}"
    ansible_user: "{{ usuario }}"
  