---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:  
    - name: Check for Python
        raw: test -e /usr/bin/python
        changed_when: false
        failed_when: false
        register: check_python

